import Head from "next/head";
import Request from "../utils/requester";
import Image from "next/image";

export default function Home({ data }) {
  console.log(data);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello World</h1>
    </div>
  );
}

// This function gets called at build time
export async function getStaticProps() {
  try {
    // Call an external API endpoint to get posts
    const [{ value: data }] = await Promise.allSettled([
      Request({
        method: "GET",
        url: `http://localhost:1337/api/homes?populate=deep`,
      }),
    ]);

    // By returning { props: { posts } }, the Blog component
    // will receive `posts` as a prop at build time

    return {
      props: {
        data: {
          components: data ? data.data : [],
        },
      },
    };
  } catch (error) {
    console.log(error);
    return {
      props: {
        data: { components: [] },
        error: true,
      },
    };
  }
}
